name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./Chapter01/UnitTest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Chapter01/UnitTest
    - name: Build => Chapter01/UnitTest
      run: dotnet build Chapter01/UnitTest --no-restore
    - name: Test => Chapter01/UnitTest 
      run: dotnet test Chapter01/UnitTest --no-build --verbosity normal
