name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_and_Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies => Chapter01/UnitTest
      run: dotnet restore Chapter01/UnitTest
    - name: Build => Chapter01/UnitTest
      run: dotnet build Chapter01/UnitTest --no-restore
    - name: Test => Chapter01/UnitTest 
      run: dotnet test Chapter01/UnitTest --no-build --verbosity normal
    
    - name: Restore dependencies => Chapter04/UnitTest
      run: dotnet restore Chapter04/UnitTest
    - name: Build => Chapter04/UnitTest
      run: dotnet build Chapter04/UnitTest --no-restore
    - name: Test => Chapter04/UnitTest 
      run: dotnet test Chapter04/UnitTest --no-build --verbosity normal

    - name: Restore dependencies => Chapter05/UnitTest
      run: dotnet restore Chapter05/UnitTest
    - name: Build => Chapter05/UnitTest
      run: dotnet build Chapter05/UnitTest --no-restore
    - name: Test => Chapter05/UnitTest 
      run: dotnet test Chapter05/UnitTest --no-build --verbosity normal

    - name: Restore dependencies => Chapter06/UnitTest
      run: dotnet restore Chapter06/UnitTest
    - name: Build => Chapter06/UnitTest
      run: dotnet build Chapter06/UnitTest --no-restore
    - name: Test => Chapter06/UnitTest 
      run: dotnet test Chapter06/UnitTest --no-build --verbosity normal
